language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vijay20886/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vijay20886/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-eu-west-2-795670526764"
  bucket_path: "docker2"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
